//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class aula
    {
        public int id { get; set; }
        public string nome_disciplina { get; set; }
        public int quantidade_aluno { get; set; }
        public string nome_professor { get; set; }
        public string nome_faculdade { get; set; }
    }
}
